server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quintanaatomas/esp-back-i-parcial
          default-label: main
          force-pull: true
          search-paths: config